spring:
  application:
    name: "configserver"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  profiles:
    active: git # Git means that the configuration files will be read from a remote Git repository instead of the local file system.
    #active: native # Native means that the configuration files will be read from the local file system (src/main/resources/config) instead of a remote repository.
  cloud:
    config:
      server:
#        native:
#          #search-locations: "classpath:/config" # This specifies the location where the configuration files are stored. In this case, it points to the "config" directory within the classpath (src/main/resources/config).
#           search-locations: "file:///Users//sandeepsagar//Development_Projects//config" # This specifies the location where the configuration files are stored. In this case, it points to the "config" directory in the current working directory (./config).
         git:
          uri: "https://github.com/SANDEEP4396/microservices-config.git"
          default-label: main
          timeout: 5
          force-pull: true # This forces the configuration server to pull the latest changes from the Git repository every time it serves a configuration request. This ensures that the server always provides the most up-to-date configuration, even if there have been changes to the repository since the last pull.
          clone-on-start: true # If this is not set to true, the configuration server will not clone the Git repository at startup. Instead, it will wait until the first request is made to fetch the configuration.
           #Setting this to true ensures that the repository is cloned and ready to serve configuration requests as soon as the server starts.
server:
  port: 8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
# We need to set up encryption and decryption for sensitive configuration properties, such as database credentials or API keys. This is done by specifying the encryption key in the configuration server's application.yml file. The "encrypt.key" property is used to define the key that will be used for encrypting and decrypting sensitive properties. This key should be kept secure and should not be hardcoded in the source code. Instead,
  #it can be provided through environment variables or externalized configuration to ensure that it is not exposed in version control systems.
encrypt:
  key: "12Hdgw82hs8263gdnla9t82h8s7d6f5g4h3j2k1l0" # This is a sample encryption key. In a real application, you should use a strong and secure key, and it should be kept confidential. You can generate a secure key using tools like OpenSSL or use a key management service to store and manage your encryption keys securely.