spring:
  application:
    name: "config-server"
  profiles:
    active: git # Git means that the configuration files will be read from a remote Git repository instead of the local file system.
    #active: native # Native means that the configuration files will be read from the local file system (src/main/resources/config) instead of a remote repository.
  cloud:
    config:
      server:
#        native:
#          #search-locations: "classpath:/config" # This specifies the location where the configuration files are stored. In this case, it points to the "config" directory within the classpath (src/main/resources/config).
#           search-locations: "file:///Users//sandeepsagar//Development_Projects//config" # This specifies the location where the configuration files are stored. In this case, it points to the "config" directory in the current working directory (./config).
         git:
          uri: "https://github.com/SANDEEP4396/microservices-config.git"
          default-label: main
          timeout: 5
          force-pull: true # This forces the configuration server to pull the latest changes from the Git repository every time it serves a configuration request. This ensures that the server always provides the most up-to-date configuration, even if there have been changes to the repository since the last pull.
          clone-on-start: true # If this is not set to true, the configuration server will not clone the Git repository at startup. Instead, it will wait until the first request is made to fetch the configuration.
           #Setting this to true ensures that the repository is cloned and ready to serve configuration requests as soon as the server starts.
server:
  port: 8071